DROP database IF EXISTS DB_2024;
CREATE database IF NOT EXISTS DB_2024;
USE DB_2024;
CREATE TABLE branch (`name` varchar(10), city varchar(20), director varchar(20), assets integer);
create TABLE FoodTable (food varchar(10), price decimal(5,2), qty integer);
describe branch;
drop table FoodTable;
alter table branch add column zip integer;
alter table branch drop column zip;
insert into branch values ('branch 1', 'Athlone', 'J.Blogg', 70), ('branch 2', 'Ballinasloe', 'Pat Mc', 500);
insert into branch values ('branch 3', 'Dublin', 'J.Public', 15);
insert into branch (`name`, city, director) values ('branch 4', 'Mullingar', 'J.Dolan'),  ('branch 5', 'Athlone', 'D.Lennon');
select * from branch where city like '%lin%';
select distinct city from branch;
select * from branch order by city;
select count(assets) from branch;
select sum(assets) from branch;
select avg(assets) from branch;
select count(distinct city) from branch;
select city, sum(assets) as TotalAssets from branch group by city;
select director, city, sum(assets) as TotalAssets from branch group by director, city;
select director, city, sum(assets) as TotalAssets from branch group by director, city having sum(assets) > 5;
select director, city, sum(assets) as TotalAssets from branch group by director, city with rollup;
